# Generated by Django 4.2.5 on 2023-09-11 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadedSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('file', models.FileField(upload_to='downloads/')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
