# Generated by Django 4.2.5 on 2023-09-11 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloadedsong',
            name='file',
            field=models.FileField(upload_to='songs/'),
        ),
    ]
